#!/usr/bin/env bash

help(){
    cat<<__EOF__
    usage:  m say [ message ]

    Examples:
      m say "hello"    # says hello
__EOF__
}

case $1 in
    help)
        help
        ;;
    *)
        say $@
        ;;
esac

# vim: ts=4 sw=4 softtabstop=4 expandtab