#!/usr/bin/env bash

help(){
    cat<<__EOF__
    usage:  m automator [ help ]

    Examples:
      m automator ~/Desktop/screensaver.workflow    # runs an automator workflow
__EOF__
}

automator(){
  /usr/bin/automator "${1}"
}

case $1 in
    help)
        help
        ;;
    *)
        automator "$@"
        ;;
esac

# vim: ts=4 sw=4 softtabstop=4 expandtab