#!/usr/bin/env bash

help(){
    cat<<__EOF__
    usage:  m macrodroid [ help ]

    Examples:
      m macrodroid "identifier" "device_id"                                  # triggers a macrodroid macro
      m macrodroid "identifier" "device_id" "param1=value1&param2=value2"    # triggers a macrodroid macro with parameters
__EOF__
}

macrodroid(){
  echo "Triggering Macro..."
  curl -i "https://trigger.macrodroid.com/${2}/${1}?{3}"
}

case $1 in
    help)
        help
        ;;
    *)
        macrodroid "$@" "$@" "$@"
        ;;
esac

# vim: ts=4 sw=4 softtabstop=4 expandtab