#!/usr/bin/env bash

help(){
    cat<<__EOF__
    usage: m bluetooth [ status | on | enable | off | disable | help ]

    Examples:
      m bluetooth status    # bluetooth status
      m bluetooth on        # turn on bluetooth
      m bluetooth enable    # turn on bluetooth
      m bluetooth off       # turn off bluetooth
      m bluetooth disable   # turn off bluetooth
__EOF__
}

#DAEMON=`[ -e /usr/sbin/bluetoothd ] && echo bluetoothd || echo blued`

case $1 in
    help)
        help
        ;;
    status)
        defaults read /Library/Preferences/com.apple.Bluetooth ControllerPowerState | \
            awk '{ if($1 != 0) {print "Bluetooth: ON"} else { print "Bluetooth: OFF" }  }'
        ;;
    on|enable)
        # Get current working directory
        BASEDIR=$(dirname "$0")

        if [ "$BASEDIR" == "." ]; then
           BASEDIR=$(pwd)
        fi

        # Turn on bluetooth
        $BASEDIR/blueutil -p 1
        ;;
    off|disable)
        # Get current working directory
        BASEDIR=$(dirname "$0")

        if [ "$BASEDIR" == "." ]; then
           BASEDIR=$(pwd)
        fi

        # Turn on bluetooth
        $BASEDIR/blueutil -p 0
        ;;
    *)
        help
        ;;
esac

# vim: ts=4 sw=4 softtabstop=4 expandtab
