#!/bin/bash

# Set terminal color
printf "\033[1;36;48m" ; clear

# Get current working directory
BASEDIR=$(dirname "$0")

if [ "$BASEDIR" == "." ]; then
   BASEDIR=$(pwd)
fi

# Enable current user
clear;
echo "o------------------------------------------------------------------o";
echo "| macOS IFTTT Control Installer                               v1.0 |";
echo "o------------------------------------------------------------------o";
echo "|                                                                  |";
echo "|   The user '$USER' has been enabled for macOS IFTTT Control";
echo "|                                                                  |";
echo "o------------------------------------------------------------------o";

cp "$BASEDIR/daemon/co.abdyfran.macosiftttcontrol.plist" ~/Library/LaunchAgents/co.abdyfran.macosiftttcontrol.plist
launchctl load ~/Library/LaunchAgents/co.abdyfran.macosiftttcontrol.plist
